# Generated by Django 3.2.10 on 2022-02-12 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orgatask.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=orgatask.models.get_default_team_settings)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', models.JSONField(blank=True, default=orgatask.models.get_default_user_settings)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orgatask_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Besitzer'), ('admin', 'Administrator'), ('member', 'Mitglied')], default='member', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orgatask.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_instances', to='orgatask.user')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Key')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('read', models.BooleanField(default=True, verbose_name='Read permission?')),
                ('write', models.BooleanField(default=False, verbose_name='Write permission?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgatask_apikeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
    ]
