# Generated by Django 3.2.10 on 2022-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgatask', '0003_calendar_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
