# Generated by Django 3.2.10 on 2022-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgatask', '0004_rename_title_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='invite',
            name='uses_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
