# Generated by Django 3.2.10 on 2022-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgatask', '0004_auto_20220608_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings_darkmode',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
