# Generated by Django 4.1 on 2022-09-04 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orgatask", "0005_user_settings_darkmode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "color",
                    models.CharField(blank=True, default="#FFFFFF", max_length=20),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todolists",
                        to="orgatask.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "ToDo-Liste",
                "verbose_name_plural": "ToDo-Listen",
            },
        ),
        migrations.CreateModel(
            name="ToDoListItem",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgatask.user",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orgatask.user",
                    ),
                ),
                (
                    "todolist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orgatask.todolist",
                    ),
                ),
            ],
            options={
                "verbose_name": "ToDo-Listeneintrag",
                "verbose_name_plural": "ToDo-Listeneinträge",
            },
        ),
    ]
