# Generated by Django 4.2.7 on 2023-11-25 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teamized", "0004_clubmember_portfolio_biography_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_owned_teams_override",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Maximale Anzahl eigener Teams",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teamized_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Django-Benutzer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="settings_darkmode",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Dunkelmodus"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
    ]
