# Generated by Django 5.2.4 on 2025-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamized", "0008_clubattendanceevent_clubattendanceeventparticipation"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="unit_count",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
