# Generated by Django 6.0.1 on 2026-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamized", "0009_worksession_unit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="portfolio_groups",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Gruppen"),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="portfolio_nickname",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Spitzname"),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="portfolio_show_age",
            field=models.BooleanField(default=False, verbose_name="Alter anzeigen?"),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="portfolio_visible",
            field=models.BooleanField(default=False, verbose_name="Portfolio sichtbar?"),
        ),
    ]
