# Generated by Django 6.0.1 on 2026-01-26 20:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamized", "0010_add_portfolio_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert am"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="member",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert am"),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="team",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert am"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert am"),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert am"),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
    ]
