# Generated by Django 6.1 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamized', '0011_various_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(default='UsersIcon', max_length=100),
        ),
    ]
